### ISSUE TITLE
Commentable configuration file

### ISSUE THREAD

**Issue by ggueret** [UbiCastTeam/mediaserver-client#4]
The current configuration file contains a lot of useful comments. But unfortunately the syntax on file preview is broken on GitHub, which make sense since JSON are made to handle data only.
Currently a workaround was made to clean comments before loading the config file, there : https://github.com/UbiCastTeam/mediaserver-client/blob/75e744b76c224ccc4932d19087691ddc93a19fad/ms_client/lib/configuration.py#L23.

Is it feasible to use an alternative like YAML or GSON ? The disadvantages are obviously to use an additional external package but it may be a plus for a better reading and a simpler code on config loading ?

**Comment by sdiemer** [comment]
I think the better thing to do is to use a Python file for the base configuration.

**Comment by sdiemer** [comment]
I have make the changes:
89c4079e7d3b51a0ccac85bd75d38286761cf19f
