### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by fthiery** [UbiCastTeam/mediaserver-client#5]
Should we not use importlib ? Is there any risk ? importlib was added in python 3.1.

```
/usr/lib/python3.7/site-packages/ms_client/lib/configuration.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```

**Comment by ggueret** [comment]
I am convinced that we must change this, imp is deprecated since version 3.4 of Python.
Any PR @fthiery ? otherwise I can do it !

**Comment by fthiery** [comment]
Please do, thx

**Comment by ggueret** [comment]
Just pushed PR https://github.com/UbiCastTeam/mediaserver-client/pull/7
