### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by ggueret** [UbiCastTeam/mediaserver-client#6]
Currently, there is no entry in docs on how to install this library to make it work.

So I typed `pip install mediaserver-client`, but "No matching distribution found for mediaserver-client", using PyPI.

As a workaround, I used the following command to install it from GitHub to the master branch: `pip install git+https://github.com/UbiCastTeam/mediaserver-client`

Should not the package be available on PyPI? In the meantime, I add an entry in the documentation to install it from a VCS using pip. A PR will follow this ticket.

**Comment by nikaro** [comment]
Here is the PyPI package: https://pypi.org/project/mediaserver-api-client/

You can see the "pypi" badge one the README.

You can also see in the Makefile the command used to publish the package. An improvement would be to automate the publication of new versions using Travis-CI or GitHub Actions.

**Comment by ggueret** [comment]
Alright, so the package on PyPI is not called as the same as the VCS repository; which can lead to confusion if you are not using badges links and just copy past the project name.

As an additional way to quickly install the package, I updated the README to add an entry about the mediaserver-client installation of the latest release from PyPI and as a development version.

https://github.com/UbiCastTeam/mediaserver-client/pull/8
